services:
  db:
    image: postgres:16-alpine
    container_name: ttirring-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ttirring
      POSTGRES_PASSWORD: ttirringpw
      POSTGRES_DB: ttirring
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: ttirring-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
