name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # postinstall 훅으로 인한 혼선을 막기 위해 스크립트 무시
      - name: Install dependencies
        run: |
          set -euxo pipefail
          npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Sanity check (files & package)
        run: |
          set -euxo pipefail
          echo "=== CWD ==="; pwd
          echo "=== ROOT LIST ==="; ls -la
          echo "=== PRISMA DIR ==="; ls -la prisma || true
          test -f prisma/schema.prisma || (echo "::error file=prisma/schema.prisma::schema.prisma not found" && exit 1)
          node -e "const p=require('./package.json'); console.log({deps:p.dependencies,devDeps:p.devDependencies,scripts:p.scripts})"

      # 권한 보정 + npx로 직접 실행(로컬 bin 미의존)
      - name: Prisma validate & generate
        env:
          DATABASE_URL: "file:./prisma/dev.db"
        run: |
          set -euxo pipefail
          # (A) 혹시 있을 로컬 바이너리 권한 보정 (있어도 되고 없어도 됩니다)
          if [ -f ./node_modules/.bin/prisma ]; then chmod +x ./node_modules/.bin/prisma || true; fi
          ls -l ./node_modules/.bin || true
          # (B) 로컬 bin 대신, npx로 지정 버전 실행 → 권한문제 회피
          npx -y prisma@6.15.0 --version
          npx -y prisma@6.15.0 validate --schema=prisma/schema.prisma
          npx -y prisma@6.15.0 generate --schema=prisma/schema.prisma

      - name: Import check (server entry)
        run: |
          set -euxo pipefail
          node -e "import('./server/server.js').then(()=>console.log('Import OK')).catch(e=>{console.error(e); process.exit(1);})"

      - name: Final verdict
        run: echo "✅ CI PASSED"
