name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run tests
        env:
          PORT: 0
          NODE_ENV: test
        run: npm test

      - name: Show coverage if exists
        if: always()
        run: |
          if [ -f coverage/lcov.info ]; then
            echo "coverage found"
            sed -n '1,200p' coverage/lcov.info | head -n 20 || true
          else
            echo "no coverage directory"
          fi
