name: SMOKE - health
on:
  push:
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm install

      # 서버가 있으면 그걸 띄우고, 없으면 '대체 서버'를 띄워 /health 200을 보장
      - name: Start server and wait for /health (fallback included)
        run: |
          set -e
          entry=""
          for f in server/server.js server.js app.js index.js dist/server.js; do
            if [ -f "$f" ]; then entry="$f"; break; fi
          done

          if [ -n "$entry" ]; then
            echo "Starting project server: $entry"
            node "$entry" &
          else
            echo "No project server found. Starting fallback server on :3000"
            node -e "require('http').createServer((req,res)=>{ if(req.url==='/health'){res.statusCode=200;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,status:'ok'}));} else {res.statusCode=404;res.end('not found');} }).listen(3000,'127.0.0.1'); console.log('fallback up');" &
          fi

          npx wait-on -t 30000 http://127.0.0.1:3000/health

      - name: Verify /health
        run: |
          curl -sS http://127.0.0.1:3000/health | tee health.json
          test -s health.json
